---
title: "Acknowledgements"
output: html_document
---

### Authorship

+ *Model development* : Miquel De Cáceres & Antoine Cabon (CTFC-CEMFOR/CREAF)
+ *User interface*: Miquel De Cáceres & Antoine Cabon (CTFC-CEMFOR/CREAF)

### Data sources

+ Information elaborated using daily weather data obtained from the [Agencia Estatal de Meteorologia (AEMET)](http://www.aemet.es).
+ Historic (1990-2015) weather data obtained from the [Agencia Estatal de Meteorologia (AEMET)](http://www.aemet.es) and [Servei Meteorologic de Catalunya (SMC)](http://www.meteo.cat).
+ Climate scenarios (2006-2100) downloaded from [Earth System Grid Federation (ESGF)](http://esgf.llnl.gov/).

### Scientific advisory board

+ Jordi Martínez Vilalta (UAB/CREAF)
+ Maurizio Mencuccini (ICREA)
+ Lluís Coll (CTFC-CEMFOR/CREAF)
+ Juli G. Pausas (CIDE-CSIC)
+ Pere Casals (CTFC-CEMFOR)
+ Lluís Brotons (CTFC-CEMFOR/CREAF/CSIC)
+ Pilar Llorens (IDAEA-CSIC)
+ Rafael Poyatos (CREAF)
+ Albert Álvarez (CREAF)
+ Jordi Vayreda (CREAF)
+ Mario Beltrán (AGS-CTFC)


### Funding projects

*Project grants*: CGL2014-59742-C2-2-R (Ministerio de Economía y Ciencia).

*Fellowships*: RYC-2012-11109 to M. De Cáceres (Ministerio de Economía y Ciencia).

---